kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: XiwocGpca+vvnuTE1CI/OKJBUCyt9JW7qqbYGuo5Wcs=
      - identity: {}
